CREATE TABLE PRODUCT(
          PRODUCT_ID VARCHAR2(20) CONSTRAINT PK_PROID PRIMARY KEY,
          P_NAME VARCHAR2(30) CONSTRAINT NN_PNAME NOT NULL,
          PRICE NUMBER CONSTRAINT NN_PRICE NOT NULL,
          DESCRIPTION VARCHAR2(100)
);

INSERT INTO PRODUCT VALUES('nb_ss7', '삼성노트북',1570000,'시리즈 7');
INSERT INTO PRODUCT VALUES('nb_ama4','맥북에어',1200000,'xcode 4');
INSERT INTO PRODUCT VALUES('pc_ibm','ibmPC',750000,'windows8');
COMMIT;

SELECT * FROM PRODUCT;